# Generated by Django 5.1.3 on 2025-05-14 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dissertation', '0002_course_yearofstudy_student_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_dissertation.course')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_groups', to='student_dissertation.student')),
                ('members', models.ManyToManyField(related_name='project_groups', to='student_dissertation.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_dissertation.yearofstudy')),
            ],
        ),
    ]
