# Generated by Django 5.1.3 on 2025-05-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dissertation', '0005_remove_document_student_document_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_milestones', to='student_dissertation.projectgroup'),
            preserve_default=False,
        ),
    ]
