# Generated by Django 5.1.3 on 2025-05-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dissertation', '0006_milestone_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_milestones', to='student_dissertation.projectgroup'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='student_dissertation.student'),
        ),
    ]
