# Generated by Django 5.1.3 on 2025-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dissertation', '0007_alter_milestone_group_alter_milestone_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='students',
            field=models.ManyToManyField(related_name='groups', to='student_dissertation.student'),
        ),
    ]
