# Generated by Django 5.1.3 on 2025-05-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dissertation', '0008_projectgroup_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='students',
        ),
    ]
