# Generated by Django 5.1.3 on 2025-05-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dissertation', '0010_filerepository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerepository',
            name='project',
        ),
        migrations.AddField(
            model_name='filerepository',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='student_dissertation.projectgroup'),
        ),
        migrations.AddField(
            model_name='filerepository',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='student_dissertation.student'),
        ),
    ]
